---

- name: Playbook for Installing DOMjudge on a Debian Server
  hosts: all_hosts
  become: true

  vars_prompt:
    - name: username
      prompt: "Enter a username to create a user fo Domjudge"
      private: no
    - name: user_password
      prompt: "Please enter your password for the Domjudge user"
      private: yes

  vars_files:
    - vault.yml

  roles:
    - role: common
    - role: domjudge-user
    - role: domjudge-server-build
    - role: domjudge-db
    - role: domjudge-web
    - role: domjudge-judgehost-build
    - role: domjudge-judgedaemon


  tasks:
  - name: Reset Domjudge admin password
    ansible.builtin.command:
      cmd: ./bin/console domjudge:reset-user-password admin
      chdir: "{{ domjudge_install_path }}/webapp"
    become_user: "{{ username }}"
    register: password_reset
    # no_log: true
    become_user: "{{ username }}"
    when: reset_admin_password | default(false)
    changed_when: true

  - name: Get Password
    ansible.builtin.debug:
      msg: "{{ password_reset.stdout | split ('[OK]') | last | trim }}"
    register: output

  - name: Extract and store new admin password
    ansible.builtin.copy:
      content: "{{ output.msg }}\n"
      dest: /home/{{ username }}/Domjudge/webpassword.txt
      mode: '0600'
    # no_log: true

